
module.exports = {
    PLAYER_SPEED: 3,
    BULLET_SPEED: 10,
    PLAYER_HEALTH: 100,
    ZOMBIE_HEALTH: 100,
    ZOMBIE_DAMAGE: 1,
    BULLET_DAMAGE: 20,
    ZOMBIES_PER_WAVE: 5,
    GAME_TICK: 1000 / 60,
    MAP_WIDTH: 800,
    MAP_HEIGHT: 600
};
